[
    {
      surveyShortName: "INFO",
      fieldName: "INFO_1",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 1,
      surveyId: "6768c63cf78939e82de0537b",
    },
    {
      surveyShortName: "INFO",
      fieldName: "INFO_2",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 11,
      surveyId: "6768c63cf78939e82de0537b",
    },
    {
      surveyShortName: "INFO",
      fieldName: "INFO_3",
      dataType: "Date",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 21,
      surveyId: "6768c63cf78939e82de0537b",
    },
    {
      surveyShortName: "INFO",
      fieldName: "INFO_4",
      dataType: "Date",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 31,
      surveyId: "6768c63cf78939e82de0537b",
    },
    {
      surveyShortName: "INFO",
      fieldName: "INFO_5",
      dataType: "String",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 41,
      surveyId: "6768c63cf78939e82de0537b",
    },
    {
      surveyShortName: "CONSENT",
      fieldName: "CONSENT_1_CONSENT",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 51,
      surveyId: "6768c63cf78939e82de0537c",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_1_InicialesdesunombrecompletoEjAntonioRui",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 61,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_2_Favordeindicarfecha",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 71,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_3_Correoelectronico",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 81,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_4_NiveldeHospitalenelquelabora",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 91,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_5_Hospitalenelquelabora",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 101,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_6_Otroespecifique",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 111,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_7_EspecialidadSubEspecialidad",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 121,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_8_Otroespecifique",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 131,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_9_AnodeResidenciaEjR1R2",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 141,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "FICHA",
      fieldName: "FICHA_10_Universidaddonderealizosucarrerademedici",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 151,
      surveyId: "6768c63cf78939e82de0537d",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_1_Edad",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 161,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_2_Sexo",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 171,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_3_Nacionalidad",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 181,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_4_Estadocivil",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 191,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_5_Numerodehijos",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 201,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_6_Ingresofamiliarmensualaproximado",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 211,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_7_Actualmentepagaalguntipoderentaocredito",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 221,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_8_Siespecifiquecantidadpromediomensualenp",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 231,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_9_Tieneintencionderealizaralgunasubespeci",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 241,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_10_EnmielecciondecarreraMedicinafuemiopcion",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 251,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_11_Surelacionconalgunapersonaosituacioncerc",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 261,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_12_Senalelapersonaquemayorpesotuvoensumomen",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 271,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_13_Otroespecifique",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 281,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_14_Durantesuvidahatenidoalgunproblemadesal",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 291,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_15_Padecealgunaenfermedad",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 301,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_16_Siespecifique",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 311,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_17_Especifiquedequetipo",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 321,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_18_Siaplicaespecifique",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 331,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_19_Hasidohospitalizadoalgunavez",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 341,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_20_Cuantotiempodurosuhospitalizacion",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 351,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_21_Siaplicaespecifique",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 361,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "SOCIODEMO",
      fieldName: "SOCIODEMO_22_NumerodeinmunizacionescontraSARS-CoV-2",
      dataType: "String",
      outputAsReal: true,
      showInSurveyOutputScreen: true,
      displayType: {
        type: "asIs",
      },
      position: 371,
      surveyId: "6768c63cf78939e82de0537e",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_1_1Mesientoemocionalmenteagotadopormitraba",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 381,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_2_2Cuandoterminomijornadadetrabajomesiento",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 391,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_3_3Cuandomelevantoporlamananaymeenfrentoao",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 401,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_4_4Sientoquepuedoentenderfacilmentealospac",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 411,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_5_5Sientoqueestoytratandoaalgunospacientes",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 421,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_6_6Sientoquetrabajartodoeldiaconlagentemec",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 431,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_7_7Sientoquetratoconmuchaeficacialosproble",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 441,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_8_8Sientoquemitrabajomeestadesgastando",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 451,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_9_9Sientoqueestoyinfluyendopositivamenteen",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 461,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_10_10Sientoquemehehechomasduroconlagente",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 471,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_11_11Mepreocupaqueestetrabajomeesteendureci",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 481,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_12_12Mesientoconmuchaenergiaenmitrabajo",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 491,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_13_13Mesientofrustradoenmitrabajo",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 501,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_14_14Sientoqueestoydemasiadotiempoenmitraba",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 511,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_15_15Sientoquerealmentenomeimportaloqueleso",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 521,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_16_16Sientoquetrabajarencontactodirectoconl",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 531,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_17_17Sientoquepuedocrearconfacilidadunclima",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 541,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_18_18Mesientoestimadodespuesdehabertrabajad",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 551,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_19_19Creoqueconsigomuchascosasvaliosasenest",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 561,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_20_20Mesientocomosiestuvieraallimitedemispo",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 571,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_21_21Sientoqueenmitrabajolosproblemasemocio",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 581,
      surveyId: "6768c63cf78939e82de0537f",
    },
    {
      surveyShortName: "CM",
      fieldName: "CM_22_22Meparecequelospacientesmeculpandealgun",
      dataType: "Integer",
      outputAsReal: false,
      showInSurveyOutputScreen: false,
      displayType: {
        type: "asIs",
      },
      position: 591,
      surveyId: "6768c63cf78939e82de0537f",
    },
  ]