export const CONFIGS_ADDRESS_STATES_REQUEST = 'CONFIGS_ADDRESS_STATES_REQUEST'
export const CONFIGS_ADDRESS_STATES_SUCCESS = 'CONFIGS_ADDRESS_STATES_SUCCESS'
export const CONFIGS_ADDRESS_STATES_FAILED = 'CONFIGS_ADDRESS_STATES_FAILED'
export const CONFIGS_ADDRESS_STATES_RESET = 'CONFIGS_ADDRESS_STATES_RESET'  
