export const SCHEDULE_DETAILS_REQUEST = 'SCHEDULE_DETAILS_REQUEST'
export const SCHEDULE_DETAILS_SUCCESS = 'SCHEDULE_DETAILS_SUCCESS'
export const SCHEDULE_DETAILS_FAIL = 'SCHEDULE_DETAILS_FAIL'

export const SCHEDULE_UPDATE_REQUEST = 'SCHEDULE_UPDATE_REQUEST'
export const SCHEDULE_UPDATE_SUCCESS = 'SCHEDULE_UPDATE_SUCCESS'
export const SCHEDULE_UPDATE_FAIL = 'SCHEDULE_UPDATE_FAIL'
