export const SRV_BLANK_CONCAT_2NDROW_PREVIOUS_HEADER = 'SRV_BLANK_CONCAT_2NDROW_PREVIOUS_HEADER'
export const SRV_SECOND_ROW_HAS_HEADERS = 'SRV_SECOND_ROW_HAS_HEADERS' 
export const SRV_CONCAT_1STROW_HEADER_2NDROW_HEADER = 'SRV_CONCAT_1STROW_HEADER_2NDROW_HEADER'
export const SRV_FIRST_ROW_HAS_HEADERS = 'SRV_FIRST_ROW_HAS_HEADERS'
