/** @format */

export const SURVEY_PROCESS_ANSWERS_REQUEST = 'SURVEY_PROCESS_ANSWERS_REQUEST'
export const SURVEY_PROCESS_ANSWERS_SUCCESS = 'SURVEY_PROCESS_ANSWERS_SUCCESS'
export const SURVEY_PROCESS_ANSWERS_FAIL = 'SURVEY_PROCESS_ANSWERS_FAIL'
export const SURVEY_PROCESS_ANSWERS_RESET = 'SURVEY_PROCESS_ANSWERS_RESET'
export const SURVEY_PROCESS_ANSWERS_STATUS = 'SURVEY_PROCESS_ANSWERS_STATUS'

export const SURVEY_DETAILS_REQUEST = 'SURVEY_DETAILS_REQUEST'
export const SURVEY_DETAILS_SUCCESS = 'SURVEY_DETAILS_SUCCESS'
export const SURVEY_DETAILS_FAIL = 'SURVEY_DETAILS_FAIL'
export const SURVEY_DETAILS_RESET = 'SURVEY_DETAILS_RESET'

export const SURVEY_OUTPUTS_REQUEST = 'SURVEY_OUTPUTS_REQUEST'
export const SURVEY_OUTPUTS_SUCCESS = 'SURVEY_OUTPUTS_SUCCESS'
export const SURVEY_OUTPUTS_FAIL = 'SURVEY_OUTPUTS_FAIL'
export const SURVEY_OUTPUTS_RESET = 'SURVEY_OUTPUTS_RESET'

export const SURVEY_OUTPUTS_EXPORT_FILE_REQUEST =
   'SURVEY_OUTPUTS_EXPORT_FILE_REQUEST'
export const SURVEY_OUTPUTS_EXPORT_FILE_SUCCESS =
   'SURVEY_OUTPUTS_EXPORT_FILE_SUCCESS'
export const SURVEY_OUTPUTS_EXPORT_FILE_FAIL = 'SURVEY_OUTPUTS_EXPORT_FILE_FAIL'
export const SURVEY_OUTPUTS_EXPORT_FILE_RESET =
   'SURVEY_OUTPUTS_EXPORT_FILE_RESET'
export const SURVEY_OUTPUTS_EXPORT_FILE_STATUS =
   'SURVEY_OUTPUTS_EXPORT_FILE_STATUS'

export const SURVEY_OUTPUT_SINGLE_REQUEST = 'SURVEY_OUTPUT_SINGLE_REQUEST'
export const SURVEY_OUTPUT_SINGLE_SUCCESS = 'SURVEY_OUTPUT_SINGLE_SUCCESS'
export const SURVEY_OUTPUT_SINGLE_FAIL = 'SURVEY_OUTPUT_SINGLE_FAIL'
export const SURVEY_OUTPUT_SINGLE_RESET = 'SURVEY_OUTPUT_SINGLE_RESET'
