/** @format */

export const SURVEY_PROCESS_ANSWERS_REQUEST = "SURVEY_PROCESS_ANSWERS_REQUEST";
export const SURVEY_PROCESS_ANSWERS_SUCCESS = "SURVEY_PROCESS_ANSWERS_SUCCESS";
export const SURVEY_PROCESS_ANSWERS_FAIL = "SURVEY_PROCESS_ANSWERS_FAIL";
export const SURVEY_PROCESS_ANSWERS_RESET = "SURVEY_PROCESS_ANSWERS_RESET";
export const SURVEY_PROCESS_ANSWERS_STATUS = "SURVEY_PROCESS_ANSWERS_STATUS";
